version: "3.8"

services:

  postgres_db:
      image: postgres
      container_name: multimatics_postgres
      environment:
        - POSTGRES_DB=my_postgres_db
        - POSTGRES_USER=myuser
        - POSTGRES_PASSWORD=mypassword
      ports:
        - "5434:5432"
      networks:
        - multimatics
      volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  flask-app:
    build: .
    restart: always
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql+psycopg2://myuser:mypassword@multimatics_postgres:5432/my_postgres_db

    ports:
      - "21099:21099"
    networks:
      - multimatics
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  multimatics: